feat: add Go and Python to linting guideline
GoogleCloudPlatform/samples-style-guide pull request #127
Opened 2023-06-13 18:18 UTC by grayside

This is a combined update for Python & Go, so it needs LGTM from members of each language team.

2023-06-23 00:03 UTC, iennae requested changes
I think this needs additional context. I literally went to the URLs mentioned and I couldn't find specifically linting guidance from the front page for Go. If we send folks to a different page we should really make sure it has the guidance they need.

2023-06-23 00:06 UTC, iennae commented
Python does have linting guidance, but we should still say a little more context. 

Something like 

Follow the guidance as per the Python style guide on linting https://google.github.io/styleguide/pyguide#21-lint with the recommended lint configuration https://google.github.io/styleguide/pylintrc (is that actually our recommendation) 

For Go, I don't know what we're trying to point to here.

2023-07-10 20:46 UTC, telpirion approved these changes

2023-07-10 20:53 UTC, telpirion commented
> I think this needs additional context. I literally went to the URLs mentioned and I couldn't find specifically linting guidance from the front page for Go. If we send folks to a different page we should really make sure it has the guidance they need.

That really is the best starting point for "official" Go guidance, with the other potential source being [Effective Go](https://go.dev/doc/effective_go).

2023-10-20 21:10 UTC, grayside commented
More specifically, you can preview this change at https://googlecloudplatform.github.io/samples-style-guide/previews/PR-127/#linting

2023-10-20 21:16 UTC, engelke commented on content/en/_index.md
> +All Python samples should follow the best practices defined in the [PEP 8](https://www.python.org/dev/peps/pep-0008/) style guide and the [Google Python Style Guide](http://google.github.io/styleguid
Remove the Google Python Style Guide. It conflicts with our standard style (such as indentation amount). For public samples, we follow the public Python PEP guide.

2023-10-20 21:17 UTC, engelke requested changes
Please remove Google style guide reference. See comment.

2023-10-20 21:22 UTC, grayside commented on content/en/_index.md
> +All Python samples should follow the best practices defined in the [PEP 8](https://www.python.org/dev/peps/pep-0008/) style guide and the [Google Python Style Guide](http://google.github.io/styleguid
```suggestion
All Python samples should follow the best practices defined in the [PEP 8](https://www.python.org/dev/peps/pep-0008/) style guide.
```

2023-10-20 21:24 UTC, engelke approved these changes
LGTM

2023-11-17 01:16 UTC, iennae approved these changes
LGTM

2023-11-17 03:43 UTC, merged